# -*- coding: utf-8 -*-
"""diabetes

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1twbLQLKDJIadM7Mkg8GjqsGFfkF4RTQa
"""

import pickle
import numpy as np
import streamlit as st

# load save model
model = pickle.load(open('diabetes.sav', 'rb'))

# judul web
st.title('Prediksi Diabetes')
Age = st.number_input('Masukan Umur')

Pregnancies = st.number_input('Jumlah Kehamilan')

Glucose = st.number_input('Konsentrasi Glukosa 2 jam Dalam Tes Toleransi Glukosa Oral')

BloodPressure = st.number_input('Tekanan Darah Diastorik (mm Hg)')

SkinThickness = st.number_input('Ketebalan Lipatan Kulit')

Insulin = st.number_input('2-Jam Serum Insulin (mu U / ml)')

BMI = st.number_input('Indek Massa Tubuh(berat dalam kg / (tinngi dalam m))')

DiabetesPedigreeFunction = st.number_input('Riwayat Keturunan Diabetes')

#code for prediction
diabetes_diagnosis =''

#membuat tombol prediksi
if st.button('ESTIMASI'):
      diabetes_diagnosis = model.predict(
            [[Pregnancies, Glucose, BloodPressure, SkinThickness, Insulin, BMI, DiabetesPedigreeFunction, Age]]
      )

      st.write ('ESTIMASI', diabetes_diagnosis)